environments {
    default {
       "base_url_clockify"  = "https://api.clockify.me/api/v1"
       "api_key" = "MzcwOWVmZjUtNGE1ZC00MGNlLWEyZTQtYTU3N2YxMTFiMmIw"
       "workspace_id" = "6925c01313ecba2b56b58cfb"
    
    }
    
    test {
       "base_url_clockify"  = "https://api.clockify.me/api/v1"
       "api_key" = "MzcwOWVmZjUtNGE1ZC00MGNlLWEyZTQtYTU3N2YxMTFiMmIw"
       "workspace_id" = "6925c01313ecba2b56b58cfb"
    }

    dev {
       "base_url_clockify"  = "https://api.clockify.me/api/v1"
       "api_key" = "MzcwOWVmZjUtNGE1ZC00MGNlLWEyZTQtYTU3N2YxMTFiMmIw"
       "workspace_id" = "6925c01313ecba2b56b58cfb"
    }
}